// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// this contains every single random phrase. spoilers ahead!
// 
// 
// 			███████        ███████    
// 		 █████████████  █████████████ 
// 		████    ██████████████    ████
// 		███       ██████████       ███
// 		████       ██    ██       ████
// 		 ████████  █      █  █████████
// 		 ████████████    ████████████ 
// 		   ██████   ██████   ██████   
// 			████     ████     ████    
// 			  ██████████████████      
// 				████      ████        
// 				  ████  ████          
// 					██████            
// 					  ██               
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// 
// ...
// 
// I can handle the truth. 
// 
// 
// 
// 
// 
// 
// 
// 
// 
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
function random(lower_bound, upper_bound) {
    return Math.round(Math.random() * (upper_bound - lower_bound) + lower_bound);
}

var phrases = [
    "fuzzy sun, get you one by one",
    "it's all downhill from here",
    "i've got reservations about so many things, but not about you",
    "is this thing on?",
    "woof",
    "every song is a comeback",
    "you can come by any time you want",
    "distance has no way of making love understandable",
    "references, references! what are your sexual preferences?",
    "if i am a dog then shake hands",
    "it's yr show",
    "you're history and i'm tapped",
    "But Have You Seen My Records?",
    "hello i am a dog yes",
    "gold star for robot boy",
    "well you better go back to beautiful texas oklahoma kansas georgia tennessee",
    "do you know how i feel?",
    "these are only lyrics now",
    "perfect always takes so long because it don't exist",
    "strange things happen for no reason",
    "hold my breath, i hold my breath, i hold it",
    "tell my mother i'm going home",
    "i'm on a need to know basis",
    "years ago they tried to put me in a payphone",
    "dont look at me!",
    "eep!",
    "You Are NOT on Wyit Dot Dog.",
    "i need to write more quotes. these ones keep repeating",
    "too much is not enough",
    "this is the life",
    "it's time to get away!",
    "this world will give you anything as long as you will want to",
    "you've got no bait attached!",
    "fooled animal, bite its tail",
    "we need so damn many things",
    "i'm okay, let me go, go away, i'm alright",
    "is steely dan still together",
    "what year is it",
    "a world awake now sleeps",
    "nowhere to go, nothing to do",
    "i want to live!!!",
    "play it cool",
    "you know i'll always be proud of you",
    "why do you do what they tell you?",
    "surely there's got to be something here, right?",
    "if you wait long enough, they will give you something",
    "nothing worth understanding",
    "in dog we trust",
    "made you look!",
    "easy there partner",
    "are you lost?",
    "hey there stranger",
    "is this what you're looking for?",
    "did you find what you sought?",
    "are you enjoying this?",
    "woah there pardner!",
    "EXACTLY WHAT YOU RUN FROM YOU END UP CHASING",
    "FLEUR&yours",
    "CLOSE THE WORLD, OPEN THE FuNK",
    "??????????????????????????????????",
    "5_38 AM ú Aug 29, 2021",
    "oops",
    "unstillness, unstillness.",
    "and yet so-",
    "in cadence as a brush that swept softly",
    "WHO ARE YOU_",
    "drown",
    "alt)ure",
    "the unballad, the unode, the unpoem",
    "!",
    "an outstreched hand from chryvaliaumae",
    "in trance under_spell",
    "in under and over the uncadentic cover inspell tentative",
    "lunar light blinds the couloir en plight",
    "EAST ?? EAST ?? BACK",
    "gazing under the sondersun",
    "uyo",
    "the unpresence (reset.)",
    "oyu",
    "a never ending cacophony of fractalized passersby",
    "there is no end to the rabbit hole there is no end to the rabbit hole",
    "i'm i'm confused confused again again",
    "spiralxspiral",
    "DON'T - DON'T - SHOOT",
    "fluttered just right",
    "loicoru couloir",
    "TO DECONSTRUCT A SLIDER",
    "whispers in the walls whispers in the walls",
    "a sickly soft strand of hair spills onto my neck",
    "an exodus of pink blinds my eye with a spell",
    "THERE WILL BE NO NEED TO DECONSTRUCT REALITY UNLESS INSTRUCTED OTHERWISE",
    "an unforgiving crystalline parts my skin painting it red so faintly",
    "The m_rror ­ observe before i wish myself a goodnight's sleep",
    "gyros ad infinitum",
    "unmaterialized_ clench glittx r&l xngs unstill, you are evil",
    "love from unknown, the under and above, it's unover",
    "REBOUND_ RISE!",
    "a folded intracanva",
    "an unperfection of the saunter",
    "pseudotwinkle",
    "you are the center of the universe",
    "wwrite mmy ooveroover ooversmear ooversmear ooversmear",
    "o",
    "you quiver with a cinch to a touch of no malice",
    "l'shroud of sequential secrets",
    "the humbling ashes of a smoldering archive",
    "i fade",
    "069",
    "an unyielding solacexsolitude",
    "??????????????????",
    "flowing down and around my neck the tears smell so saccharine",
    "constranoco over honnostone",
    "a drowning within the mental spiral",
    "a dystopian over-commute xv",
    "WoN'T x WoN'T x U TELL ME ALLABOUT iT_",
    "like curious angels flowering the night",
    "the forlorned word that had been whispered through me",
    "cccccccuttttthroughhhtttheeennnoiseeeppppppleassssse",
    "couloir no color ad monochrvme, a blinding course",
    "traces of my breaths linger my soul",
    "in this infinite, regal ballroom",
    "a cryptic spore in time encapsulated in an hourglass",
    "unxygotic exotic exorcisms over xnor",
    "in the thick air of a hallucinogen and in the dense fog of the night i roam",
    "hyourvoyc resounsibnthe nyte",
    "haunt me, hurt me",
    "xhirne-type nusphera infestation, class ???",
    "tears twinkle under skyscraper lights",
    "an absence of light comes an abscess of darkness",
    "wander in the wonder of these endless corridors",
    "on the softness of noise",
    "the cocoon of silence",
    "close your eyes",
    "chimera in nothing",
    "an abstract cadence of decadence",
    "i peel at myself; withering away and to whimper",
    "overconvergence",
    "l'est i'm ever so~",
    "all is but the asphalt of aspera",
    "eyes that hath been vlinnd by the heav'ns blu.",
    "melt under rot",
    "a sense of wonder in the dust",
    "a ladder rasping in that vast array of lasting static",
    "believeme when isay_ _there's millions ofus_ _justlike you",
    "zero information",
    "wyit",
    "an erudite composition",
    "underpastellation",
    "THIS?WAY?NOT?THERE?",
    "FLORAxGrotessquelation",
    "that one damn strand of hair.",
    "a sunset, sickly so",
    "withering under the dimming of the world",
    "a shadow i left before me and after you",
    "it's a never ending street of lights i'll never understand",
    "the persistence of unperfection",
    "an unsaunthering, unseething eye",
    "a cognitive crystal blooms in this moment",
    "his cold demeanor melts like ice cream on my lips",
    "an event, unchanging, ever annual.",
    "the tools of repetition exist before you and after me",
    "in memoriam_ olc. when the time comes, we will welcome you with open arms",
    "time faltering retires your verdict unto which i cannot enter.",
    "no use crying over spilt emotion",
    "fireworks and shooting stars, where humanity aligns with the sun",
    "tear away my tears of paint",
    "zero motivation, one hundred determinations",
    "dim the lights and play",
    "empty",
    "shattered fragments of myself",
    "a sweet haunting thru the noise",
    "your artificial folds allure me",
    "the smoke that smells so saccharine and so sweet",
    "a rift blooms in your plane of time",
    "take care of yourself",
    "stroeliziae",
    "flourished never brandished",
    "a thick fog lingers in my eye",
    "an efflorescent ocean of light",
    "overuse, overwork, overloaded",
    "it's so cold...",
    "fluorescent flora basking under light",
    "you left me an imperfect recollection",
    "er_er_er_er",
    "i sold my scrolls for some sapphire souls",
    "the touch of a cold, tender hand",
    "she throws me in all southward directions at once",
    "abrasion in the skies",
    "the ashing sand between our toes",
    "lingering souls, haunting rooms",
    "our names in neon lights, flustering in hollywood",
    "gray regality.",
    "unsober",
    "adorn me",
    "beneath glistering waves",
    "scorched under light i burn",
    "focus.",
    "decorate pop separate",
    "After ? Party",
    "treading between two waters",
    "a soul begins to rot in the walls",
    "ashes, ashes",
    "you withered me to my shadows",
    "how my soul drowns in you",
    "hearts beating in the powerlined skies",
    "`twas left a starving wounded soul",
    "a pool of rose colored noise",
    "listlessly listlessly",
    "tides steeped with roses",
    "sqew",
    "the love that swirled in your breath",
    "with a knife and chisel i carved your warmth into my flesh",
    "painterly blueberries",
    "2 22 22 22 2 22",
    "thank you for the wishes",
    "i am healing",
    "spl!nt±r",
    "gunning down the macerators",
    "i stretched my hand into the void",
    "linei ad complekt",
    "eternal whirlwind",
    "the sparks and candy that scorched my tongue",
    "a flame that singes and kisses my skin",
    "A CAPTURED MOMENT OF WHIRLITUDE",
    "fin g er ti p      s",
    "i am",
    "mending, i",
    "happy birthday, pastry of pastries",
    "shards of nature",
    "these darklights that shine seep through my eyes",
    "trillvthrill",
    "oozing pastellactites",
    "not szo szhiny",
    "????",
    "lucid overtones",
    "fall upon my warmth",
    "upright and upwritten shards shed by wings above",
    "one last moment of reality",
    "WHAT ARE YOU RUNNING FROM_",
    "knit falls",
    "in silk, sin ilk",
    "this is beginning to get on my nerves.",
    "venistrxtive",
    "bluly nested cliffs up that way over north",
    "to two for two to two too to two too",
    "glazed sunwaters",
    "tie me with your cords of noise and silence",
    "a melting hall",
    "barefinger murder",
    "petal, nothing",
    "a kidnapping in secret sands",
    "mysubconsciousmindw_rld",
    "weep not, my dear",
    "a shapeless form",
    "up over and back around to you",
    "visions of a wandering eye",
    "ÛÛÛÛÛÛÛÛÛ",
    "to melt the words onto your neck",
    "growth",
    "iridescent spillover",
    "boredom is angst simply being shy",
    "goodnight",
    "a_tokai",
    "fa‡ade",
    "BReakdown, baby!",
    "i can barely keep cons c i o  u   s",
    "as the city falls to consciousness",
    "Make sure you typed the name correctly, and then try again.",
    "abandon",
    "Don't ask for my address, you'd never make it",
    "vices in the night",
    "Untitled",
    "SuperStar??!",
    "realit„t",
    "there are ways to keep me out of here",
    "i'm running out of spells",
    "fall",
    "edito",
    "in your eyes melt my flesh",
    "forgiveness, the",
    "the man of your doorstep",
    "and surely this was inevitable",
    "how they scream in any which direction",
    "tell us a truth",
    "speak of what you are",
    "Smear! Smear! Smear!",
    "where sky met ground",
    "decadent death of a blur",
    "lost your grip on life",
    "Truth",
    "bleeding by a thread",
    "hhey",
    "radiance",
    "i could be anywhere but here",
    "azure eyes_hidden knowledge",
    "life in alters",
    "YOUR DEVICE IS ON THE LINE. RESPONSE MAY BE RECORDED.",
    "wilting sunglasses",
    "A7AE4B76912F2D3EB7CC59187677CBDEB1C8797B0714F99A490FA77C5FBAAE04",
    "shifting starlights",
    "broken beacons",
    "wrong with my face",
    "a haze of my own volition",
    "this certain death",
    "pulsating 8",
    "deepsea freefall",
    "lycanthrope misanthrope",
    "feels like a floor",
    "unwave",
    "SWEETSWEETSWEET",
    "chrysalizing",
    "lycanthropic dunes",
    "p?q?n?s?p 'p??dn?s?p",
    "living lift aloft",
    "pulsating 7",
    "critical shard",
    "kill",
    "on core",
    "everything is soon to fall away",
    "bled eye",
    "concealed nothing",
    "photographed popcorn",
    "absurd&segmented",
    "pixels.within.pixels",
    "pulsating 6",
    "mith moth",
    "breathing carnage",
    "asphoriation",
    "Shockwave",
    "critical error",
    "cascades",
    "a disputed shore",
    "overstimulated",
    "reflexion sunset",
    "enter the floodgates",
    "pulsating 5",
    "pulsating 4",
    "ungridded",
    "overthreaded",
    "lathered luridity",
    "0x80004005",
    "cyclocean",
    "an irreparable sentia",
    "this profound depthness",
    "the intangibility of nil",
    "faire point",
    "a city without dreams",
    "the frontier before endlessness",
    "SUMMER LIFE ISOLATIONISM GIGATRAP MIX.HEIC",
    "element;murder",
    "could this possibly last forever",
    "Focused on the Next Second",
    "twisted, garbled.",
    "snowy nights",
    "televortex",
    "nil forever",
    "obscura reflex",
    "hold it close",
    "ashes and void",
    "all we do, we do for our image",
    "a dank riverside",
    "xxxxxxx",
    "rustblue",
    "12",
    "i hid my shards",
    "since you fell",
    "barricaded",
    "truly, truly, truly",
    "behind closed doors",
    "despite everything,",
    "nearing a fatal end",
    "HX_X",
    "hide me more",
    "a fleeting bliss state",
    "favorite fabrics",
    "coutura",
    "sunset end",
    "laps around the city",
    "time, as a flat circle",
    "blanket, stat warm",
    "light slips a.way",
    "Untitled",
    "unfortunate xx",
    "OPENING STATEMENT",
    "Take Love Break Me",
    "the somnambulist's ballad",
    "ode to self",
    "this path you cannot change",
    "written pages unending",
    "a sleepwalker's transit",
    "the abyss's glare",
    "Denha",
    "fifteen cascades",
    "fourteen cascades",
    "escape to bleak",
    "but you let it die",
    "iudicium finale",
    "do not let it die",
    "the ghost of your aria sings in vain",
    "non-light",
    "in - between",
    "IN THE FACE OF",
    "this eclipse i burden betrays me",
    "era",
    "ode.",
    "static in your pattern",
    "pastel noise",
    "SELF",
    "eon of wind",
    "the ink flows from the wound on my chest",
    "confronting waste",
    "fair'st point",
    "in the incessant search for that which is meaning",
    "fair p'int",
    "the human form exhausts the soul",
    "nova",
    "derail monodetail",
    "nonadent",
    "sserafh",
    "you, through stormy eyes",
    "lay it out on me",
    "lay all your love on me",
    "you are not obligated to make any sense to the universe",
    "offerings",
    "cry on my behalf",
    "for it never sounds of you",
    "it is simply what i am trained to do",
    "cranial",
    "on this perfect planet",
    "tell me, art.",
    "excerpt of samsara",
    "4_44_17-4_44_38 PM_ 1,371,928,747 ANRETRIBUTIONS",
    "burning of the ashes",
    "rutensuru, the road over",
    "??",
    "carpe amorem",
    "memory nmeshed",
    "banished to the throws, requiem of my self",
    "noise partition",
    "all thunder in flux by principle",
    "a suspended disbelief",
    "the howls",
    "ceremutrails",
    "Shattering Shards of Samsara Univers",
    "mbrace",
    "through eyes like these",
    "false globe",
    "noisal",
    "fabricon",
    "atomization of euthymia",
    "refraction of thought",
    "companionship",
    "our cathedrals",
    "sounds like a hell",
    "catacomb visions",
    "kirei na sankaku",
    "asahi ningen",
    "not used to the festive mood",
    "Untitled",
    "metasquare",
    "shattering of fate",
    "ripples that can count to three",
    "removed memory",
    "uncooked grain",
    "happy birthday",
    "flag_cn",
    "conjoined novas",
    "matrices",
    "half geometry",
    "with",
    "marks",
    "crane in the sky",
    "crane in the sky II",
    "intentional of That and This,",
    "roots descending",
    "removed memory increased distance",
    "stand your ground",
    "found it slow",
    "viscapparel",
    "up to the flesh",
    "rootworks",
    "LINUX",
    "hydro residuals",
    "molten ocean",
    "miscellany",
    "vacher",
    "extremities as well",
    "non-there",
    "closed source",
    "this atonement",
    "babelist",
    "reconverge",
    "out of mind",
    "five six physic",
    "drole",
    "when do you cry",
    "utils",
    "thymes",
    "bluish",
    "repent",
    "most ignoble fringes",
    "noirceur",
    "consume anger etc.",
    "???",
    "ONETWOTHREEFOUR",
    "MOVE NEXT, AND THIS",
    "To view keyboard shortcuts, press question mark",
    "Peril",
    "original clouds",
    "????",
    "soul shred now",
    "answer, no answer",
    "in this marble",
    "to this end",
    "all knowing hand",
    "You are here. -_",
    "happy birthday to me",
    "pink alt cover",
    "???????????",
    "two tone undertone",
    "light surface underside",
    "Lisa",
    "yuube",
    "frailty",
    "mortality",
    "2ness",
    "parking without regard",
    "not much there",
    "half tech",
    "him",
    "season",
    "artisan",
    "graphicaloader",
    "abberate",
    "belle",
    "risk",
    "candid",
    "it longed now",
    "matter of perspective",
    "observance",
    "fixtures",
    "televisions",
    "no remorse",
    "windows on windows",
    "seven heart bleedings",
    "the shocks (how to fall again)",
    "None St.",
    "refleksive",
    "the views",
    "i found sola",
    "hi_ hi.",
    "r hour",
    "oxidation",
    "rvoad",
    "burn",
    "loath",
    "exit",
    "cause and effect",
    "why us_",
    "light painter",
    "this over nature",
    "6 46",
    "phsntom",
    "'p N-rhxlv2pivrl",
    "Apt' T ]]vHqvh]] io Qr-Ver. 22",
    "C--qlo. Qo . ren]ding 08",
    "PARA(ISO)",
    "linsocholy. (I _ __R)",
    "??",
    "moon in your reflection",
    "make it mine",
    "garbage",
    "dizzy",
    "cuts cuts & cuts",
    "tsyanien",
    "agrppa",
    "darling..",
    "matter of perspective",
    "lightwise",
    "cusp",
    "inverted sky",
    "ontree",
    "ossess",
    "vignetting",
    "in nature 2",
    "You seem to be in a new location",
    "noisilxochitl",
    "mindness",
    "ustic",
    "There Existed an Addiction to the Stage",
    "morose bladed",
    "char",
    "My body is failing me",
    "to another",
    "no envy",
    "come down",
    "keynote",
    "229",
    "soft",
    "phyll",
    "my health is failing me",
    "my mind is failing me",
    "Night",
    "road",
    "hook",
    "rose rose-tint",
    "ails",
    "idling",
    "metal light",
    "dolce",
    "for 15 fucking minutes i had a conversation with my hero",
    "Live in concert.",
    "de-value",
    "is this really what you deserve_",
    "dow",
    "is pain",
    "19v--=",
    "streaky",
    "matter of attack",
    "Oh where",
    "cexposure",
    "romanticize",
    "fleurilenze",
    "in these shadows, i.",
    "torrentials",
    "Friends",
    "stemmed in the madness tonight",
    "walk with it",
    "notek",
    "patina",
    "mancala",
    "Weakness is.png",
    "slider",
    "slider II",
    "slider III",
    "fairfellow",
    "slider IV",
    "meow",
    "meow II",
    "era II",
    "foundyours",
    "sadness onstage",
    "a red tone",
    "aftertone",
    "grasp it.",
    "i hope you can find it in your heart",
    "1 2 3 4 what comes after",
    "if you see this dm me 'apple' for no reward",
    "i could tell you were lonely",
    "from the moment you walked in",
    "from the way you had your makeup on",
    "from the way you'd done your hair",
    "from the way you sat down next to me",
    "from the way you ordered your drink",
    "from the moment you put your hand on my knee",
    "i knew i'd have you with ease",
    "of course, you know my name",
    "everyone does, it's true",
    "it's true, it's true, it's true",
    "that i'm known around here",
    "the barmaids know my name",
    "i've had them all before",
    "you are new, i'll have you too",
    "it's time to give in",
    "from the shores of havana",
    "to moscow and tokyo",
    "in french guianese, in cantonese",
    "everyone knows my name",
    "i'll arrive at around 7 p.m.",
    "and i want you to get there no later than 10",
    "i want you to be dressed like a sophisticated tart",
    "a solid one pound of whatever",
    "gimme a one two three",
    "got your nose!",
    "no you won't",
    "no balls",
    "i love reze",
    "私が全部教えてあげる",
    "レゼは大好き",
    "a wise man once said: 'portugal malone IV'",
    "hey girl!",
    "make it 4eva",
    "she's the serpentine she's my collar",
    "Dogphin",
    "give it to me bby",
    "real music",
    "you are on blixys dot com",
    "manic, satirical, sexual, progressive, technical, energetic, complex",
    "nothin' to be justified yet",
    "give me an 'A'",
    "people keep passing around thirsty wyatts",
    "proposing that all the snow from des moines be dumped directly on the sphere",
    "The work, which becomes a new genre itself, will be called...",
    "SEE YOU SPACE COWBOY...",
    "what's good girl",
    "i'm stuck in raising lame so i'm literally watching in silence but omg she's so queen",
    "I O U",
    "gimme an 'Awesome'",
    "an Apple copywriter once said: 'Oh. So. Pro.'",
    "an Apple copywriter once said: 'From to-do to ta-da.'",
    "an Apple copywriter once said: '1,000 songs in your pocket.'",
    "an Apple copywriter once said: 'Think different.'",
    "an Apple copywriter once said: '5G speed. OMGGGGG.'",
    "an Apple copywriter once said: 'There's an app for that.'",
    "an Apple copywriter once said: 'Here's to the crazy ones.'",
    "an Apple copywriter once said: 'The whole widget.'",
    "an Apple copywriter once said: 'Shot on iPhone.'",
    "an Apple copywriter once said: 'Lean. Mean. M3 machine.'",
    "an Apple copywriter once said: 'See tomorrow, today.'",
    "an Apple copywriter once said: 'Hello, Neo.'",
    "an Apple copywriter once said: 'The muscle for your hustle.'",
    "an Apple copywriter once said: 'Open up and say wow.'",
    "an Apple copywriter once said: 'Love at first Mac.'",
    "an Apple copywriter once said: 'A feast for the senses.'",
    "Do it.",
    "what kinda car U drive",
    "four by three",
    "sixteen by nine",
    "eleven by eight",
    "one-hundred and forty-three by one-hundred",
    "one to one",
    "it's the brand new blixys website",
    "since december twenty-second twenty-fifteen",
    "Spread the word!",
    "make us feel each other",
    "one schizophrenic versus twenty empty chairs",
    "a wise man once said: 'the creator has a master plan'",
    "where is computer number nine? we are not leaving until it's back in the cart",
    "me         we",
    "canes so ahhhh",
    "it's the new new new",
    "are you videos and games?",
    "le sigh, we cringe on",
    "good boy",
    "i've concluded this album rocks and explodes",
    "gimme a ten eleven twelve",
    "blixys.com/images/all.gif",
    "behind you",
    "boom",
    "fingers that tendon on pearlescent whiteboard",
    "twice begotten now-ashened limerence",
    "a wise man once said: 'But what love got to do with it when you don't love yourself?'",
    "repost if you dip your boobs in the wendy's frosty",
    "listen to good kid, m.A.A.d city",
    "five hundred cigarettes",
    "JFK once said: 'one thousand cuban cigars mister salinger'",
    "'Welling and swelling I bear in the tide.'- Maya Angelou",
    "'The apparition of these faces in the crowd:'",
    "'Petals on a wet, black bough.'",
    "also visit my friend's website, wyit.dog",
    "click the logo for a fun noise",
    "take care of yourself!",
    "she has an album to Drop Tomorrow Night and she's playing on that TikTok Phone!!!!!!!!",
    "#U",
    "https://x.com/waaaaven/status/2034384802942697859",
    "https://x.com/Insact9704/status/2034713563575853154",
    "It's what they call 'you'.",
    "You felt like, whatever you were for just right now, it might be okay.",
    "green apple redo",
    "cmon man",
    "flopping in creation is better than slaying in consumption",
    "gimme that new new new new new new new new new new new new new new new new new new new new new sound",
    "I wish U well 4eva.",
    "but I'll ignore my body 4 U.",
    "U me.",
    "tell me U want it.",
    "U.",
    "try not to smoke challenge",
    "#NY",
    "#LA",
    "#CH",
    "#HO",
    "#PX",
    "#PH",
    "#SD",
    "#DA",
    "#SF",
    "#SE",
    "#DE",
    "#DC",
    "#NV",
    "#AU",
    "#BO",
    "#LV",
    "#MI",
    "#AT",
    "#NO",
    "#PO",
    "#DT",
    "#MN",
    "#ME",
    "#BA",
    "#KC",
    "#SL",
    "#CL",
    "#PI",
    "#CI",
    "#ST",
    "#TA",
    "#OR",
    "#CC",
    "#IN",
    "#MW",
    "#RA",
    "#RI",
    "#HI",
    "#AK",
    "True",
    "#Live",
    "#Lifechangingvlog",
    "it feels like Music",
    "Everything 2 U.",
    "say hello: blixys.com/contact",
    "blixys.com/mapping.mp4",
    "don't even joke lad.",
    "guys its over",
    "Noting this down.",
    "#Dragonite",
    "https://c.tenor.com/xirdUIgHddwAAAAd/tenor.gif",
    "Gimme a #True",
    "sign on the dotted line!",
    "it's the brand new U",
    "total Knock Out",
    "there has to be a curse placed on me",
    "exulansis",
    "tellmeBUTDONTtellme",
    "a wise woman once said: 'I'm quite happy with my vibe'",
    "party ain't start yet",
    "mbv",
    "arf! ar-arf!",
    "let's make the Pentagon broke af",
    "Let's just do something absolutely crazy",
    "tried applying for a face card",
    "#Hollywood",
    "make it forever",
    "brick",
    "dont U wanna.",
    "eat plenty of yogurt",
    "Are you Ken Feelin it?",
    "https://x.com/itserrepe/status/2034851664729948318",
    "a wise woman once said: 'U need to BRING the deodorant TO the show in a LITTLE BAG'",
    "don't think twice! do think twice! ahoooo!",
    "https://x.com/underscoresplus/status/1955324396421120135",
    "her ears are out for an amazing reason",
    "Did yall hear that (Noise)",
    "C18H24O2",
    "Estra-1,3,5(10)-triene-3,17β-diol",
    "i like Music",
    "U. it's brand New.",
    "it's coffee time",
    "the U machine.",
    "we Yearn on...",
    "i wonder if U can tell which ones were written in 2021-24 versus 2026",
    "i mean it should be pretty obvious",
    "drop on hollywood forever is a healing experience",
    "build & drop on innuendo (i get U) is a visceral experience",
    "he wasted the other £2 million",
    "a wise wyit once said to me: 'your achilles heel is a beautiful woman with black hair'",
    "One Thousand Lines",
    "'yeah, i bet you'd fuck anything with a heartbeat' -underscores",
    "they're playing heat waves in this fkn raising canes it's so over",
    "bumpin that",
    "its gonna be a U spring",
    "art Deco is our Destiny",
    "When on Wli",
    "souljaboytankem",
    "Why do people keep crashing into CVS?",
    "https://youtu.be/4p8JhIzmkco",
    "the first ever music",
    "the first ever funny moment",
    "underscores funny moments",
    "real music",
    "family guy scary moments",
    "$10000000 Candles",
    "that's my floor",
    "Check out my latest beat-map: O:/osu!/Exports/a3 piano - F. Chopin - Etude Op. 10 No. 4 Torrent.osz",
    "i wanna dance 2 U.",
    "under_loadscores",
    "The Peace.",
    "Junkie church sunday service",
    "visit wyit dot dog as well",
    "My Office",
    "you are currently on https://blixys.com",
    "Home run!",
    "_ _ _ <- underscores",
    "shoutouts to wyit",
    "shoutouts to downpour",
    "shoutouts to Kataryn",
    "shoutouts to ancel",
    "shoutouts to ben",
    "shoutouts to Ralkinson",
    "shoutouts to tobuFI",
    "shoutouts to ScubDomino",
    "shoutouts to -Arko",
    "shoutouts to Ksardas",
    "shoutouts to rrtyui",
    "shoutouts to Stormbird",
    "shoutouts to 6pXgEj3hc7Umj5H",
    "shoutouts to fanzhen0019",
    "shoutouts to hamano",
    "shoutouts to KomachiBaka",
    "shoutouts to kuyusu",
    "shoutouts to pishifat",
    "shoutouts to Beomsan",
    "shoutouts to over_loadcode",
    "shoutouts to wafer",
    "shoutouts to tatemae",
    "shoutouts to dsco",
    "shoutouts to Drimm",
    "shoutouts to seros",
    "shoutouts to pocket-",
    "shoutouts to Hollow Wings",
    "shoutouts to rustbell",
    "shoutouts to Haruto",
    "shoutouts to 1103",
    "shoutouts to Fisky",
    "shoutouts to squirrelpascals",
    "shoutouts to jamesjan3",
    "shoutouts to FetherFall",
    "shoutouts to Coz",
    "shoutouts to ztrot",
    "shoutouts to colicen",
    "shoutouts to azphyx",
    "shoutouts to theedoo",
    "shoutouts to calyx1220",
    "we want God's Plan",
    "turn the volume up",
    "TURN UP OR DIE",
    "euphoria",
    "it's me and U.",
    "boba time!",
    "how am i supposed to flirt with THIS barista?",
    "call me retreats",
    "(Can't run from the urge)",
    "0.28% chance it's Halloween",
    "glass me",
    "Ah!",
    "software my melodies",
    "kissing 101",
    "kissing 207",
    "heads OR tails.",
    "heads",
    "tails",
    "you drew an ace of hearts!",
    "you drew a two of hearts!",
    "you drew a three of hearts!",
    "you drew a four of hearts!",
    "you drew a five of hearts!",
    "you drew a six of hearts!",
    "you drew a seven of hearts!",
    "you drew an eight of hearts!",
    "you drew a nine of hearts!",
    "you drew a ten of hearts!",
    "you drew a jack of hearts!",
    "you drew a queen of hearts!",
    "you drew a king of hearts!",
    "you drew an ace of diamonds!",
    "you drew a two of diamonds!",
    "you drew a three of diamonds!",
    "you drew a four of diamonds!",
    "you drew a five of diamonds!",
    "you drew a six of diamonds!",
    "you drew a seven of diamonds!",
    "you drew an eight of diamonds!",
    "you drew a nine of diamonds!",
    "you drew a ten of diamonds!",
    "you drew a jack of diamonds!",
    "you drew a queen of diamonds!",
    "you drew a king of diamonds!",
    "you drew an ace of clubs!",
    "you drew a two of clubs!",
    "you drew a three of clubs!",
    "you drew a four of clubs!",
    "you drew a five of clubs!",
    "you drew a six of clubs!",
    "you drew a seven of clubs!",
    "you drew an eight of clubs!",
    "you drew a nine of clubs!",
    "you drew a ten of clubs!",
    "you drew a jack of clubs!",
    "you drew a queen of clubs!",
    "you drew a king of clubs!",
    "you drew an ace of spades!",
    "you drew a two of spades!",
    "you drew a three of spades!",
    "you drew a four of spades!",
    "you drew a five of spades!",
    "you drew a six of spades!",
    "you drew a seven of spades!",
    "you drew an eight of spades!",
    "you drew a nine of spades!",
    "you drew a ten of spades!",
    "you drew a jack of spades!",
    "you drew a queen of spades!",
    "you drew a king of spades!",
    "we make magic!",
    "i gotta write three more lines",
    "so dumbbbbb",
    "blixys.com/puzzle01.png",
    "congratulations! you just stumbled on the thousandth phrase. dm me 'real moment' for emotional validation"
];

var wyitPhrase = phrases[random(0, phrases.length - 1)]
var aText = [ wyitPhrase ];
var iSpeed = random(15,75); 
var iIndex = 0; 
var iArrLength = aText[0].length; 
var iScrollAt = 20;
var iTextPos = 0; 
var sContents = ''; 
var iRow;

function typewriter()
{
 sContents =  ' ';
 iRow = Math.max(0, iIndex-iScrollAt);
 var destination = document.getElementById("typedtext");
 
 while ( iRow < iIndex ) {
  sContents += aText[iRow++] + '<br />';
 }
 destination.innerHTML = sContents + aText[iIndex].substring(0, iTextPos) + " ♦";
 if ( iTextPos++ == iArrLength ) {
  iTextPos = 0;
  iIndex++;
  if ( iIndex != aText.length ) {
   iArrLength = aText[iIndex].length;
   setTimeout("typewriter()", 500);
  }
 } else {
  setTimeout("typewriter()", iSpeed);
 }
}
window.onload = function() {
    typewriter();
};